export default {
    id: "1",
    title: "首页配置",
    name: null,
    type: "home",
    component: [
        {
            "name": "头部",
            "title": "头部",
            "component": "dz-head",
            "container": false,
            "type": "base",
            "icon": "search-line",
            "enableCustomTemplate": false,
            "props": {
                "spacing": 10,
                "value": "",
                "shape": "round",
                "inputAlign": "left",
                "isDiy": 1,
                "isLeft": 1,
                "leftType": "2",
                "leftText": "logo",
                "leftStyle": {
                    "fontSize": 16,
                    "color": "#333",
                    "isBold": 1
                },
				"cover":"/static/logo.png",
                "coverWidth": 200,
				"coverHeight":55,
                "borderRadius": 0,
                "isRight": 1,
                "rightType": "2",
                "rightStyle": {
                    "fontSize": 19,
                    "color": "#333"
                },
                "bgColor": "#f3f4f6",
                "topBottom": 6,
                "leftRight": 12
            },
            "offsetTop": 0,
            "offsetLeft": 10,
            "data": {}
        },
		{
		    "name": "下拉加载",
		    "title": "下拉加载",
		    "component": "wwj-loading",
		},
		/* {
		    "name": "搜索",
		    "title": "搜索",
		    "component": "dz-search",
		    "container": false,
		    "type": "base",
		    "icon": "search-line",
		    "enableCustomTemplate": false,
		    "props": {
		        "spacing": 10,
		        "value": "",
		        "shape": "square",
		        "inputAlign": "left",
		        "isDiy": 1,
		        "coverSize": 30,
		        "borderRadius": 0,
		        "bgColor": "#fff",
		        "searchBgColor": "#fff",
		        "topBottom": 6,
		        "leftRight": 10
		    },
		    "offsetTop": 0,
		    "offsetLeft": 10,
		    "data": {
		        "hot_search_default": "",
		        "hot_search_list": [
		            "日用品",
		            "布公仔"
		        ]
		    }
		}, */
        
		{
		    "name": "导航",
		    "title": "导航",
		    "component": "dz-grid-menu",
		    "container": false,
		    "icon": "grid-fill",
		    "type": "base",
		    "enableCustomTemplate": true,
		    "props": {
		        "col": "4",
		        "isPage": "1",
		        "isName": 1,
		        "widthHeight": 45,
		        "borderRadius": 10,
		        "radius": 10,
		        "topBottom": 8,
		        "leftRight": 10,
		        "bgColor": "#fff",
		        "dotColor": "red",
		        "mode": "round",
		        "colNum": 1,
		        "list": [
		            {
		                "cate_title": "口令红包",
		                "cover": "/static/image/kl.png",
		                "activeMenuType": "",
		                "delId": 0
		            },
		            {
		                "cate_title": "特惠充值",
		                "cover": "/static/image/cz.png",
		                "activeMenuType": "",
		                "delId": 1
		            },
		            {
		                "cate_title": "积分商城",
		                "cover": "/static/image/sc.png",
		                "activeMenuType": "",
		                "delId": 2
		            },
		            {
		                "cate_title": "邀请有礼",
		                "cover": "/static/image/yq.png",
		                "activeMenuType": "",
		                "delId": 3
		            },
		            {
		                "cate_title": "大神榜",
		                "cover": "",
		                "activeMenuType": "",
		                "delId": 4
		            },
		            {
		                "cate_title": "我的订单",
		                "cover": "",
		                "activeMenuType": "",
		                "delId": 5
		            }
		        ],
		        "topButtom": 0,
		        "clearance": 0
		    },
		    "offsetTop": 345,
		    "offsetLeft": 290,
		    "data": []
		},
		{
			"name": "限时折扣",
			"title": "限时折扣",
			"component": "dz-discount",
			"container": false,
			"icon": "",
			"type": "base",
			"enableCustomTemplate": true,
			"props": {
				"titleShow": 1,
				"coverShow": 0,
				"coverSize": 26,
				"title": "新手专享",
				"titleRight": "",
				"titleSize": 16,
				"titleRightSize": 14,
				"isBold": 1,
				"titleColor": "#333",
				"titleRightColor": "#333",
				"styleGroup": "slide",
				"productNameShow": 1,
				"tagShow": 1,
				"marketPriceShow": 1,
				"buttonShow": 1,
				"topBottom": 12,
				"leftRight": 12,
				"radius": 10,
				"cover": "",
				"dataSource": "manual",
				"productLimit": 3,
				"list": [{
					"marketing_type": "discount",
					"name": "智能芭比娃娃",
					"picture": "https://oss.fstaolege.com/imgs/2022/5/11/4a705e95373f41c5b50131355e765fd5.png",
					"price": "588.00",
					"market_price": "688.00",
					"total_sales": "0",
					"activeMenuType": "discount",
					"id": "101",
					"sketch": ""
				},{
					"marketing_type": "discount",
					"name": "虎年吉祥7寸娃娃",
					"picture": "https://oss.fstaolege.com/imgs/2022/5/11/89428d4032db4ff0b51dd1b9e286dda8.png",
					"price": "588.00",
					"market_price": "688.00",
					"total_sales": "0",
					"activeMenuType": "discount",
					"id": "127",
					"sketch": ""
				},{
					"marketing_type": "discount",
					"name": "鲜Q果冻爽",
					"picture": "https://oss.fstaolege.com/imgs/2022/5/11/43084d1d00c640d4be1b65cbdee4c1fc.png",
					"price": "588.00",
					"market_price": "688.00",
					"total_sales": "0",
					"activeMenuType": "discount",
					"id": "129",
					"sketch": ""
				}],
				"topButtom": 0,
				"clearance": 0
			},
			"offsetTop": 375,
			"offsetLeft": 290,
			"data": [{
				"id": "101",
				"name": "智能芭比娃娃",
				"sketch": "",
				"keywords": "",
				"picture": "https://oss.fstaolege.com/imgs/2022/5/11/4a705e95373f41c5b50131355e765fd5.png",
				"video": "http://pull.fstaolege.com/live/D019.flv",
				"view": "6",
				"match_point": "5",
				"price": 79,
				"market_price": 688,
				"cost_price": "480.00",
				"wholesale_price": "0.00",
				"stock": "222",
				"total_sales": "0",
				"shipping_type": "1",
				"unit": "",
				"is_open_member_discount": "0",
				"member_discount_type": "1",
				"marque": "b45456256",
				"discount": {
					"id": "1",
					"discount_id": "1",
					"product_id": "4",
					"discount": "80.00",
					"type": "1",
					"product_name": "五粮液-五粮浓香-壬寅虎年生肖酒-52度",
					"product_picture": "https://imgs.93kj.top/images/2022/03/24/image_1640531863_Vglm9duv.png",
					"start_time": "1651507200",
					"end_time": "1653926400",
					"decimal_reservation_number": "-1",
					"status": "1"
				}
			},{
				"id": "127",
				"name": "虎年吉祥7寸娃娃",
				"sketch": "",
				"keywords": "",
				"picture": "https://oss.fstaolege.com/imgs/2022/5/11/89428d4032db4ff0b51dd1b9e286dda8.png",
				"video": "http://pull.fstaolege.com/live/D020.flv",
				"view": "6",
				"match_point": "5",
				"price": 19,
				"market_price": 688,
				"cost_price": "480.00",
				"wholesale_price": "0.00",
				"stock": "222",
				"total_sales": "0",
				"shipping_type": "1",
				"unit": "",
				"is_open_member_discount": "0",
				"member_discount_type": "1",
				"marque": "b45456256",
				"discount": {
					"id": "1",
					"discount_id": "1",
					"product_id": "4",
					"discount": "80.00",
					"type": "1",
					"product_name": "五粮液-五粮浓香-壬寅虎年生肖酒-52度",
					"product_picture": "https://imgs.93kj.top/images/2022/03/24/image_1640531863_Vglm9duv.png",
					"start_time": "1651507200",
					"end_time": "1653926400",
					"decimal_reservation_number": "-1",
					"status": "1"
				}
			},{
				"id": "129",
				"name": "鲜Q果冻爽",
				"sketch": "",
				"keywords": "",
				"picture": "https://oss.fstaolege.com/imgs/2022/5/11/43084d1d00c640d4be1b65cbdee4c1fc.png",
				"video": "http://pull.fstaolege.com/live/D021.flv",
				"view": "6",
				"match_point": "5",
				"price": 29,
				"market_price": 688,
				"cost_price": "480.00",
				"wholesale_price": "0.00",
				"stock": "222",
				"total_sales": "0",
				"shipping_type": "1",
				"unit": "",
				"is_open_member_discount": "0",
				"member_discount_type": "1",
				"marque": "b45456256",
				"discount": {
					"id": "1",
					"discount_id": "1",
					"product_id": "4",
					"discount": "80.00",
					"type": "1",
					"product_name": "五粮液-五粮浓香-壬寅虎年生肖酒-52度",
					"product_picture": "https://imgs.93kj.top/images/2022/03/24/image_1640531863_Vglm9duv.png",
					"start_time": "1651507200",
					"end_time": "1653926400",
					"decimal_reservation_number": "-1",
					"status": "1"
				}
			}]
		},
		{
		    "name": "公告",
		    "title": "公告",
		    "component": "dz-notice-bar",
		    "container": false,
		    "type": "base",
		    "icon": "airplay-fill",
		    "enableCustomTemplate": false,
		    "props": {
		        "mode": "horizontal",
		        "volumeIcon": "1",
		        "moreIcon": 1,
		        "title": "公告",
		        "color": "#333",
		        "iconColor": "#333",
		        "bgColor": "#fff",
		        "topBottom": 8,
		        "leftRight": 12,
		        "radius": 10,
		        "titleStyle": {
		            "fontSize": 16,
		            "isBold": "1",
		            "color": "#333"
		        },
		        "cover": "",
		        "coverSize": 20
		    },
		    "offsetTop": 345,
		    "offsetLeft": 290,
		    "data": [
		        {
		            "id": "1",
		            "title": "YYDShop来了",
		            "cover": "https://yydshop-b2c.vjlau.com/attachment/images/2021/12/25/image_1640424193_p1xTZZ1h.png",
		            "synopsis": "",
		            "view": "4",
		            "created_at": "1640426478"
		        }
		    ]
		},
		{
			"name": "轮播图",
			"title": "轮播图",
			"component": "dz-swiper",
			"container": false,
			"icon": "device-fill",
			"type": "base",
			"enableCustomTemplate": true,
			"props": {
				"bgColor": "#f3f4f6",
				"borderRadius": 10,
				"mode": "slider",
				"height": 120,
				"indicatorPos": "bottomCenter",
				"effect3d": 1,
				"topBottom": 6,
				"leftRight": 10,
				"title": 0,
				"list": [{
					"searchValue": null,
					"createBy": null,
					"createTime": "2022-01-11 22:20:18",
					"updateBy": null,
					"updateTime": null,
					"remark": null,
					"isProxy": null,
					"params": {},
					"id": 4,
					// "img": "imgs/2022/5/11/3f8e536f76d845ad9f97aa4dc32f4625.png",
					"img": "imgs/2022/5/20/3b8b0347eb4f4cebb18e356505af8c3a.png",
					"title": null,
					"location": "indexCarousel",
					"jumpType": "innerPage",
					"jumpLink": "recharge",
					"status": 0,
					"sort": 1,
					"app": "testapp,hzwwc",
					"version": 0
				}]
			},
			"offsetTop": 47,
			"offsetLeft": 80,
			"data": []
		},
		 /* {
			"name": "图片广告",
			"title": "图片广告",
			"component": "dz-banner",
			"container": false,
			"type": "base",
			"icon": "image-2-fill",
			"enableCustomTemplate": false,
			"props": {
				"url": "",
				"cover": "https://imgs.93kj.top/images/2022/05/16/87991e8ce7184d0dbbd3043c86b6fd90.png?v=1",
				"height": 120,
				"leftRight": 0,
				"topBottom": 0,
				"radius": 0,
				"link": {
					"activeMenuType": "",
					"activeMenu": ""
				},
				"activeIndex": 0
			},
			"area": [],
			"offsetTop": 375,
			"offsetLeft": 290,
			"data": []
		}, */
        /* {
            "name": "图片广告",
            "title": "图片广告",
            "component": "dz-banner",
            "container": false,
            "type": "base",
            "icon": "image-2-fill",
            "enableCustomTemplate": false,
			"height": 100,
			"leftRight": 12,
			"topBottom": 0,
			"radius": 12,
            "props": {
            	"url": "",
            	"cover": "https://imgs.93kj.top/images/2022/05/16/87991e8ce7184d0dbbd3043c86b6fd90.png",
            	"height": 120,
            	"leftRight": 0,
            	"topBottom": 0,
            	"radius": 0,
            	"link": {
            		"activeMenuType": "",
            		"activeMenu": ""
            	},
            	"activeIndex": 0
            },
            "area": [],
            "offsetTop": 410,
            "offsetLeft": 360,
            "data": []
        }, */
		{
		    "name": "间隔槽",
		    "title": "间隔槽",
		    "component": "dz-gap",
		    "container": false,
		    "type": "base",
		    "icon": "checkbox-blank-fill",
		    "props": {
		        "height": 8,
		        "bgColor": null
		    },
		    "offsetTop": 209,
		    "offsetLeft": 150,
		    "data": []
		},
        {
            "name": "标配导航",
            "title": "标配导航",
            "component": "dz-section",
            "container": false,
            "type": "base",
            "icon": "input-cursor-move",
            "enableCustomTemplate": false,
            "props": {
                "title": "社区精选",
                "right": 1,
                "showLine": "0",
                "lineColor": null,
                "bgColor": null,
                "topBottom": 10,
                "leftRight": 14,
                "link": {
                    "activeMenu": "1-1",
                    "pageView": "article",
                    "pageName": "文章首页",
                    "active": 31,
                    "activeMenuType": "pageView"
                },
                "bold": "1"
            },
            "offsetTop": 521,
            "offsetLeft": 500,
            "data": []
        }, 
        {
            "name": "文章列表",
            "title": "文章列表",
            "component": "dz-article",
            "container": false,
            "type": "base",
            "icon": "list-unordered",
            "props": {
                "dataSource": "manual",
                "productLimit": 2,
                "mode": "default",
                "topBottom": 0,
                "leftRight": 12,
                "radius": 12,
                "cardMargin": 12,
                "cardPadding": 10,
                "contentPadding": 0,
                "width": 112,
                "height": 75,
                "radius1": 10,
                "radius2": 10,
                "isDescription": 1,
                "isTime": 1,
                "isViewCount": 1,
                "list": [
                    {
                        "title": "抓娃娃技巧",
                        "diyCover": "https://imgs.93kj.top/images/2022/05/16/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220516191055.png",
                        "cover": "https://imgs.93kj.top/images/2022/05/16/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220516191055.png",
                        "description": "高定香氛 指尖生香",
                        "view_count": "4",
                        "created_at": "1641352682",
                        "id": "1"
                    },
					{
					    "title": "抓娃娃大赛",
					    "diyCover": "https://p6.itc.cn/q_70/images03/20210623/4dcdd74f012f4d3392b0bc347ba5c438.gif",
					    "cover": "https://p6.itc.cn/q_70/images03/20210623/4dcdd74f012f4d3392b0bc347ba5c438.gif",
					    "description": "高定香氛 指尖生香",
					    "view_count": "4",
					    "created_at": "1641352682",
					    "id": "1"
					}
                ]
            },
            "offsetTop": 562,
            "offsetLeft": 570,
            "data": [
                {
                    "id": "103",
                    "title": "抓娃娃技巧",
                    "cover": "https://imgs.93kj.top/images/2022/05/16/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220516191055.png",
                    "cate_id": "1",
                    "description": "抓娃娃除了靠运气，也要靠一点小聪明滴",
                    "position": "0",
                    "link": "",
                    "author": "YYDShop",
                    "view_count": "7",
                    "sort": "999",
                    "status": "1",
                    "created_at": "1641352682",
                    "updated_at": "1641365333",
                    "cate": {
                        "id": "1",
                        "title": "个人美妆",
                        "sort": "999",
                        "level": "1",
                        "pid": "0",
                        "tree": "tr_0 ",
                        "status": "1",
                        "created_at": "1641352446",
                        "updated_at": "1641352446"
                    },
                    "tags": []
                },
				{
				    "id": "104",
				    "title": "线下大赛",
				    "cover": "https://p6.itc.cn/q_70/images03/20210623/4dcdd74f012f4d3392b0bc347ba5c438.gif",
				    "cate_id": "1",
				    "description": "好多小伙伴空有一副抓娃娃技能却无处展示~现在你们的机会来啦！",
				    "position": "0",
				    "link": "",
				    "author": "YYDShop",
				    "view_count": "58",
				    "sort": "999",
				    "status": "1",
				    "created_at": "1641353682",
				    "updated_at": "1641364333",
				    "cate": {
				        "id": "1",
				        "title": "个人美妆",
				        "sort": "999",
				        "level": "1",
				        "pid": "0",
				        "tree": "tr_0 ",
				        "status": "1",
				        "created_at": "1641352446",
				        "updated_at": "1641352446"
				    },
				    "tags": []
				}
            ]
        },
       {
            "name": "标题",
            "title": "标题",
            "component": "dz-title",
            "container": false,
            "type": "base",
            "icon": "edit-2-fill",
            "props": {
                "title": "娃娃推荐",
                "mode": "icon",
                "barColor": "#2979ff",
                "barBokehColor": "#f3f4f6",
                // "coverLeft": "https://yydshop-b2c.vjlau.com/attachment/images/2021/12/25/image_1640426866_XaTC51Dv.png",
                // "coverRight": "https://yydshop-b2c.vjlau.com/attachment/images/2021/12/25/image_1640426870_RvwOofzu.png",
                "fontSize": 18,
                "titleColor": "#333",
                "barWidth": 95,
                "barHeight": 8,
                "iconWidth": 60,
                "iconHeight": 34,
                "leftRight": 0,
                "paddingTop": 10,
                "paddingBottom": 10,
                "bgColor": "",
                "bold": 1,
                "textAlign": "left",
                "tipConfig": {
                    "title": "描述",
                    "status": 0,
                    "fontSize": 12,
                    "color": "#333"
                }
            },
            "offsetTop": 784,
            "offsetLeft": 640,
            "data": []
        },
        {
            "name": "商品列表",
            "title": "商品列表",
            "component": "dz-product-list",
            "container": false,
            "type": "base",
            "icon": "function-fill",
            "enableCustomTemplate": false,
            "isList": 2,
            "props": {
				"isLoading": "1",
                "productType": "product",
                "productLimit": 10,
                "dataSource": "manual",
                "leftRight": 12,
                "topBottom": 0,
                "maxHeight": 160,
                "marketPriceShow": 1,
                "clearance": 6,
                "radius": 10
            },
            "offsetTop": 840,
            "offsetLeft": 710,
            "data": []
        },
    ],
    params: "{\"auths\": [\"default\"], \"isHeight\": 0, \"pageColor\": \"#f3f4f6\", \"pageStyle\": {\"top\": 10, \"bottom\": 10, \"leftRight\": 10}, \"isNavColor\": 0, \"pageColorMode\": \"default\", \"pictureHeight\": 667, \"pageLinearColor\": {\"deg\": 0, \"deputyColor\": \"#D51010\", \"primaryColor\": \"#F04E2E\"}, \"backgroundPicture\": \"\"}",
    bottom_tabbar: "0",
    font_colour: "",
    top_colour: "",
    page_colour: "",
    background_picture: "https://yydshop-b2c.vjlau.com/attachment/images/2021/12/25/image_1640424526_yMZ6E1eV.jpg",
    is_default: "1",
    status: "1",
    created_at: "1640398140",
    updated_at: "1646013615"
}
